# Generated by Django 4.2.7 on 2023-11-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
