version: '3.8'

services:
  frontend:
    container_name: chat_frontend_container
    build:
      context: .
      dockerfile: Dockerfile 
    command: ['npm', 'run', 'dev']
    ports:
      - "5173:5173" 
    volumes:
      - .:/chat-frontend 

volumes:
  frontend_data: