# Generated by Django 4.2.7 on 2023-11-17 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0003_alter_groupchatmessage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='members',
            field=models.ManyToManyField(null=True, related_name='group_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupchatmessage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
