# Generated by Django 4.2.7 on 2023-11-24 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='members',
            field=models.ManyToManyField(related_name='group_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
